version: "3.9"
services:
  back:
    container_name: back
    build:
      context: ./server
      target: development
    depends_on:
      - "db"
    ports:
      - "5000:8080"
    command: npm run start:dev
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - postgres

  db:
    container_name: db
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user01
      POSTGRES_PASSWORD: qwertyui
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../temp:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user01 -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/test -user=user01 -password=qwertyui -connectRetries=60 migrate
    volumes:
      - /home/maks/my_project/newFolder/TEST/my_forest/migration:/flyway/sql
    depends_on:
      - db
      - back   
    networks:
      - postgres

  client:
    container_name: client
    build:
      context: ./client
    image: client
    ports:
      - '3001:3000'

networks:
  postgres:
    driver: bridge